apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-11-29T17:36:34Z"
  labels:
    app: front
  name: front-service
  namespace: default
  resourceVersion: "7065"
  uid: 38ef3fb3-fb06-49b7-8492-a70970bf3c15
spec:
  clusterIP: 10.110.250.52
  clusterIPs:
  - 10.110.250.52
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30996
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: front
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
