# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build-front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          # checks if there is a change in the package-lock.json to either use cache, or install dep
          cache-dependency-path: "./front-end/package-lock.json"
      - name: Install dependencies
        run: npm ci
        working-directory: ./front-end
      - name: Build application
        run: npm run build --if-present
        working-directory: ./front-end
      # - name: Run tests
      #   run: npm test
      #   working-directory: ./front-end

  test-and-build-default-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          # checks if there is a change in the package-lock.json to either use cache, or install dep

          cache-dependency-path: "./default/package-lock.json"
      - name: Install dependencies
        run: npm ci
        working-directory: ./default
      - name: Build application
        run: npm run build --if-present
        working-directory: ./default
      # - name: Run tests
      #   run: npm test
      #   working-directory: ./default
  test-and-build-user-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          # checks if there is a change in the package-lock.json to either use cache, or install dep

          cache-dependency-path: "./user/package-lock.json"
      - name: Install dependencies
        run: npm ci
        working-directory: ./user
      - name: Build application
        run: npm run build --if-present
        working-directory: ./user
      # - name: Run tests
      #   run: npm test
      #   working-directory: ./user
